= Arquillian Cube: Unit Tests Against Docker Images
Andy Gumbrecht, Senior Software Developer, Tomitribe

Blog source code can be found https://github.com/AndyGee/JAX/tree/master/arquillian-cube[here]

== What is Arquillian Cube?

This article assumes that you are already familiar with the http://arquillian.org[Arquillian] extensible testing platform. If not, then you
should pop over to the http://arquillian.org[Arquillian site] and learn about the http://arquillian.org/invasion/[invasion].

Arquillian Cube is an http://arquillian.org/modules/cube-extension/[extension] led by https://twitter.com/alexsotob[@alexsotob]
that enables Arquillian based unit tests against https://www.docker.com/[Docker] images, with as little overhead as possible.

== Disable TLS on Docker 1.3.x for Boot2Docker

If you are using an older version of Docker, or do not require Boot2Docker (Linux), then you can skip the actions in this section.
Please still read on, as this may affect you should you perform an upgrade in the future.

As of version 1.3.x Docker has switched to using TLS for communication with the Docker API (Secure sockets over HTTPS on port 2376).
This was an abrupt (undocumented, yet critical) change that breaks many tools that have been written for previous Docker versions.
This includes Cube.

The quickest resolution is to disable/revert TLS for the Docker API until Cube has caught up. To do this follow the steps below:

From a console type the following to access the Docker daemon shell:
----
boot2docker ssh
----
Gain root permissions:
----
sudo su -
----
Use the http://www.freebsd.org/cgi/man.cgi?query=vi[VI] text editor to edit the profile:
----
vi /var/lib/boot2docker/profile
----

Type the following in the editor:
----
DOCKER_TLS="no"
----
Press the 'ESC' key and type ZZ to save the profile and quit the vi editor

Restart the Docker daemon:
----
/etc/init.d/docker restart
----

Exit the shell
----
exit
----
Retart the Docker image:
----
boot2docker stop

boot2docker start
----

You will see something like the following. To enable access to the Docker daemon from any console you can add these
settings to your local OS environment variables:
----
To connect the Docker client to the Docker daemon, please set:
    export DOCKER_HOST=tcp://192.168.59.103:2375
    export DOCKER_CERT_PATH=''
    unset DOCKER_TLS_VERIFY
----

Run a quick test:
----
curl http://192.168.59.103:2375/_ping
----
This should respond simply with 'OK'

Note: If you do not have ´curl´ on Windows then you can download it http://curl.haxx.se/dlwiz/?type=bin&os=Win64[here]. It is a very useful
tool to have.



== Getting Started - The Usual POM Suspects

Using the blog https://github.com/AndyGee/JAX/tree/master/arquillian-cube[source code] as a reference you need to add the Cube
dependencies to your projects https://github.com/AndyGee/JAX/tree/master/arquillian-cube/pom.xml[pom.xml] in addition to the usual Arquillian dependencies (at the time of writing, version 1.0.0.Alpha5):
[source,xml]
----
    <dependency>
      <groupId>org.arquillian.cube</groupId>
      <artifactId>arquillian-cube-docker</artifactId>
      <version>1.0.0.Alpha5</version>
      <scope>test</scope>
    </dependency>
----

== The Arquillian Cube Extension

Add the Cube extension to your https://github.com/AndyGee/JAX/tree/master/arquillian-cube/src/test/resources/arquillian.xml[arquillian.xml] configuration file:

[source,xml]
----
    <arquillian xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns="http://jboss.org/schema/arquillian"
                xsi:schemaLocation="http://jboss.org/schema/arquillian
      http://jboss.org/schema/arquillian/arquillian_1_0.xsd">

      <extension qualifier="docker">
        <property name="serverVersion">1.18</property>
        <property name="serverUri">http://192.168.59.103:2375</property>
        <property name="dockerContainers">
          tomcat:
            image: andygeede/webprofile
            exposedPorts: [8080/tcp,8089/tcp,5432/udp]
            await:
              strategy: static
              ip: 192.168.59.103
              ports: [8080]
            portBindings: [8080/tcp,8089/tcp,5432/udp]
        </property>
      </extension>

      <container qualifier="tomee" default="true">
        <configuration>
          <property name="host">192.168.59.103</property>
          <property name="httpPort">8080</property>
          <property name="user">tomee</property>
          <property name="pass">unsecured</property>
        </configuration>
      </container>

    </arquillian>
----